
export const GET_REPARIERS = 'GET_REPARIERS';
export const GET_REPARIERS_BY_NAME = 'GET_REPARIERS_BY_NAME';
export const ADD_REPAIRER = 'ADD_REPAIRER';
export const DELETE_REPS = 'DELETE_REPS';
export const GET_FINISHED_DEVICES = 'GET_FINISHED_DEVICES';
export const EDIT_FINISHED_DEVICES = 'EDIT_FINISHED_DEVICES';
export const POST_FINISHED_DEVICES = 'POST_FINISHED_DEVICES';
export const GET_CENTERS = 'GET_CENTERS';
export const ADD_CENTERS = 'ADD_CENTERS';
export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_DEVICES_BEFORE_REPAIRING = 'GET_DEVICES_DEVICES_BEFORE_REPAIRING';
export const ADD_DEVICES = 'ADD_DEVICES';
export const ASSIGN_TO_CENTER = 'ASSIGN_TO_CENTER';
export const GET_CENTER_REPAIRERS = 'GET_CENTER_REPAIRERS';
export const REMOVE_REP_FROM_CENTER = 'REMOVE_REP_FROM_CENTER';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';

